class Book:
    def __init__(self,title :str ,description :str ,author :str , publish_date : str) -> None:
        self.title=title
        self.description=description
        self.author=author
        self.publish_date=publish_date


book1=Book("Anna Karenina","Anna Karenina tells of the doomed love affair between the sensuous and rebellious Anna and the dashing officer, Count Vronsky. Tragedy unfolds as Anna rejects her passionless marriage and must endure the hypocrisies of society. Set against a vast and richly textured canvas of nineteenth-century Russia, the novel's seven major characters create a dynamic imbalance, playing out the contrasts of city and country life and all the variations on love and family happiness. While previous versions have softened the robust, and sometimes shocking, quality of Tolstoy's writing, Pevear and Volokhonsky have produced a translation true to his powerful voice. This award-winning team's authoritative edition also includes an illuminating introduction and explanatory notes. Beautiful, vigorous, and eminently readable, this Anna Karenina will be the definitive text for generations to come.","Leo Tolstoy","5 October 1995")
book2=Book("The Odyssey ","The Odyssey is one of two major ancient Greek epic poems attributed to Homer. It is, in part, a sequel to the Iliad, the other work traditionally ascribed to Homer. The poem is fundamental to the modern Western canon. Indeed it is the second—the Iliad being the first—extant work of Western literature. It was probably composed near the end of the eighth century BC, somewhere in Ionia, the Greek-speaking coastal region of what is now Turkey. The poem mainly centers on the Greek hero Odysseus (or Ulysses, as he was known in Roman myths) and his long journey home following the fall of Troy. It takes Odysseus ten years to reach Ithaca after the ten-year Trojan War. In his absence, it is assumed he has died, and his wife Penelope and son Telemachus must deal with a group of unruly suitors, the Mnesteres or Proci, competing for Penelope's hand in marriage.","Homer","1614")
book3=Book("The Trial ","Written in 1914, The Trial is one of the most important novels of the twentieth century: the terrifying tale of Josef K., a respectable bank officer who is suddenly and inexplicably arrested and must defend himself against a charge about which he can get no information. Whether read as an existential tale, a parable, or a prophecy of the excesses of modern bureaucracy wedded to the madness of totalitarianism, Kafka's nightmare has resonated with chilling truth for generations of readers. This new edition is based upon the work of an international team of experts who have restored the text, the sequence of chapters, and their division to create a version that is as close as possible to the way the author left it. In his brilliant translation, Breon Mitchell masterfully reproduces the distinctive poetics of Kafka's prose, revealing a novel that is as full of energy and power as it was when it was first written.","Franz Kafka","1914")
book4=Book("The Sun Also Rises","The novel explores the lives and values of the so-called Lost Generation, chronicling the experiences of Jake Barnes and several acquaintances on their pilgrimage to Pamplona for the annual San Fermin festival and bull fights, known more commonly as the Running of the Bulls. Jake, a World War I veteran, is unable to consummate a sexual relationship with Brett Ashley because of a severe wound suffered when his fighter plane crashed on the Italian Front, leaving him emasculated. However, he is still attracted to and in love with her. The story follows Jake and his various companions across France and Spain.","Ernest Hemingway","1926")
book5=Book("One Thousand and One Nights","One Thousand and One Nights is a collection of Middle Eastern and South Asian stories and folk tales compiled in Arabic during the Islamic Golden Age. It is often known in English as the Arabian Nights, from the first English language edition (1706), which rendered the title as The Arabian Nights' Entertainment. The original concept is most likely derived from an ancient Sassanid Persian prototype that relied partly on Indian elements,[2] but the work as we have it was collected over many centuries by various authors, translators and scholars across the Middle East and North Africa. The tales themselves trace their roots back to ancient and medieval Arabic, Persian, Indian, Egyptian and Mesopotamian folklore and literature. In particular, many tales were originally folk stories from the Caliphate era, while others, especially the frame story, are most probably drawn from the Pahlavi Persian work Hazār Afsān. Though the oldest Arabic manuscript dates from the 14th century, scholarship generally dates the collection's genesis to around the 9th century. What is common throughout all the editions of the Nights is the initial frame story of the ruler Shahryar (from Persian: شهريار, meaning king or sovereign) and his wife Scheherazade (from Persian: شهرزاده, meaning townswoman) and the framing device incorporated throughout the tales themselves. The stories proceed from this original tale; some are framed within other tales, while others begin and end of their own accord. Some editions contain only a few hundred nights, while others include 1,001 or more. Some of the best-known stories of The Nights, particularly Aladdin's Wonderful Lamp, Ali Baba and the Forty Thieves and The Seven Voyages of Sinbad the Sailor, while almost certainly genuine Middle-Eastern folk tales, were not part of The Nights in Arabic versions, but were interpolated into the collection by its early European translators.","ibn almofagaa","1662")
books_list = [book1.title,book2.title,book3.title,book4.title,book5.title]
books=[book1,book2,book3,book4,book5]